blank_issues_enabled: false
contact_links:
  - name: Jellyfin server documentation
    url:  https://jellyfin.org/docs/general/getting-help.html
    about: Help with Jellyfin server setup and common server-side problems
  - name: Jellyfin server community
    url: https://jellyfin.org/contact/
    about: Community help for Jellyfin server questions
