name: Feature request
description: Request a new feature
labels:
  - enhancement
body:
  - type: checkboxes
    id: before-posting
    attributes:
      label: "Before submitting:"
      description: Please confirm the following.
      options:
        - label: I have searched existing [LumaFin feature requests](https://github.com/bagodees/LumaFin-AndroidTV/issues?q=is%3Aissue%20label%3Aenhancement) and this has not already been requested.
          required: true
  - type: textarea
    attributes:
      label: Problem description
      description: Describe the issue you are experiencing or the gap you are trying to address.
      placeholder: |
        LumaFin does not currently offer a way to …
        This makes it difficult to …
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: Provide a detailed description of what you would like to see implemented or changed.
      placeholder: |
        LumaFin could …
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: Outline any other approaches you have thought about or explored to solve the problem.
      placeholder: |
        Another approach could be …
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Include any relevant details, resources, or screenshots that might help in understanding or implementing the request.
      placeholder: Add any additional context here.
    validations:
      required: false
  - type: input
    id: other-sources
    attributes:
      label: Other sources
      description: Link related issues, mockups, or discussions, if any.
      placeholder: https://github.com/bagodees/LumaFin-AndroidTV/issues/…
    validations:
      required: false
